[language-server]
nu-lsp = { command = "nu", args = [ "--lsp" ] }

[[language]]
name = "nu"
# scope = "source.nu"
# injection-regex = "nu"
# file-types = ["nu"]
# shebangs = ["nu"]
# comment-token = "#"
# indent = { tab-width = 2, unit = "  " }
language-servers = [ "nu-lsp" ]

[[language]]
name = "rust"
language-servers = ["rust-analyzer"]

[language-server.rust-analyzer.config]
check.command = "clippy"
