[language-server]
nu-lsp = { command = "nu", args = [ "--lsp" ] }

[[language]]
name = "nu"
# scope = "source.nu"
# injection-regex = "nu"
# file-types = ["nu"]
# shebangs = ["nu"]
# comment-token = "#"
# indent = { tab-width = 2, unit = "  " }
language-servers = [ "nu-lsp" ]
